name: Release

on:
  push:
    # trigger on any tag push
    tags:
      - "v*"

concurrency:
  group: "release"
  cancel-in-progress: true

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Metadata: Git"
        id: git-meta
        uses: 'penguin-statistics/actions/git-meta@main'
      
      - name: "Docker: Build and Push Image"
        id: ghcr-docker
        uses: 'penguin-statistics/actions/ghcr-docker@main'
        with:
          version: ${{ steps.git-meta.outputs.version }}
          repository: 'penguin-statistics/widget-backend'
          build-args: |
            BUILD_DOCS_COMMIT=fb08b08f5f97e89b2407e56c20b0707f19dc8f32
            BUILD_WEB_COMMIT=d8bfdda68fde8af99b2c062a83fda7a43cf4d880

      - name: "Release: Call Dispatcher"
        id: release-dispatcher
        uses: 'penguin-statistics/actions/release-dispatcher@main'
        with:
          version: ${{ steps.git-meta.outputs.version }}
          use-ghrelease: true
          use-manifestbot: true
          manifestbot-file-path: 'applications/widget/values-prod.yaml'
          manifestbot-token: ${{ secrets.PAT_FOR_MANIFESTBOT }}
