name: Release

on:
  push:
    # trigger on any tag push
    tags:
      - "v*"

concurrency:
  group: "release"
  cancel-in-progress: true

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Get Tag Version
        id: get_version
        run: |
          export TRUNCATED_GITHUB_SHA=$(echo ${{ github.sha }} | cut -c1-7);
          echo "VERSION=${GITHUB_REF/refs\/tags\//}+${TRUNCATED_GITHUB_SHA}" >> $GITHUB_ENV
          echo "GIT_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
          # if `alpha` or `beta` is in the tag, then it will be a pre-release
          echo "PRE_RELEASE=false" >> $GITHUB_ENV
          if [[ ${GITHUB_REF} == *"alpha"* ]] || [[ ${GITHUB_REF} == *"beta"* ]]; then
            echo "PRE_RELEASE=true" >> $GITHUB_ENV
          fi

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/penguin-statistics/widget-backend:latest,
            ghcr.io/penguin-statistics/widget-backend:${{ env.GIT_TAG }}
          cache-from: type=registry,ref=ghcr.io/penguin-statistics/widget-backend:latest
          cache-to: type=inline

      - name: Create GitHub Release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: "${{ env.PRE_RELEASE }}"
